//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVISO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AVISO()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
        }
    
        public int NUMERO { get; set; }
        public int CEDULA { get; set; }
        public string TELEFONO { get; set; }
        public string NOM_LOGUEO { get; set; }
        public string COD { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual HashSet<ARTICULO> ARTICULO { get; set; }
    }
}
